### ISSUE TITLE
unable to write main.workflow problem

### ISSUE THREAD

**Issue by JonasJurczok** [ludeeus/action-push#1]
Hi,
does this action work?
I'm currently trying to push to a branch from an action and get the following error:

> [remote rejected] prepare-release -> prepare-release (refusing to allow an integration to create .github/main.workflow)

Is there a trick that you know of or is this simply a bug?

**Comment by ludeeus** [comment]
It did work last time I used it, but will have a look later today

**Comment by JonasJurczok** [comment]
Awesome, thank you.

**Comment by ludeeus** [comment]
Do you get this in the action log or somewhere else?
Are the repo public so I can see the full action log?

**Comment by JonasJurczok** [comment]
Hi,
yes it's in the action log.

Yes its public. See
https://github.com/JonasJurczok/semantic-release-kotlin/runs/81571230

Thanks for the quick response :)
Jonas

**Comment by JonasJurczok** [comment]
And this is the corresponding script file: https://github.com/JonasJurczok/semantic-release-kotlin/blob/master/.github/prepare-release.sh
(As you can see I'm currently not using your action but the same code)

**Comment by JonasJurczok** [comment]
I just checked with your action: https://github.com/JonasJurczok/semantic-release-kotlin/runs/81613729

Also fails.

**Comment by ludeeus** [comment]
https://github.com/ludeeus/ROOT/runs/81621176
I tried it now, and it works.
The mail + username you tried need to be changed.

I tried it with master, so the branch may be the issue, will test that as well

**Comment by JonasJurczok** [comment]
hmm.. strange. Which email address did you use? yours or is there a pattern for generating a made up one?

**Comment by JonasJurczok** [comment]
Also 

> On branch master
> nothing to commit, working tree clean

 :)
I assume this is why it worked

**Comment by ludeeus** [comment]
LOL... yeah...

**Comment by ludeeus** [comment]
> Which email address did you use? yours or is there a pattern for generating a made up one?

I use my own, the mail used are the one that the commit is registered as.

**Comment by JonasJurczok** [comment]
Okay. I also tried that.

My current theory is that if you push to a non existing branch you technically create a new workflow file.. and this seems to be prevented for security reasons :/

Still looks like a bug..

**Comment by JonasJurczok** [comment]
Theory proven wrong. Even pushing to an existing branch triggers the error.

The only solution would be to remove the workflow file but then I cannot trigger workflows on that branch anymore.

I'll wait for an answer from the github support then :)

**Comment by ludeeus** [comment]
That looks correct...
GH does not allow for automated creation of that file.

There is nothing I can do about that.

**Comment by JonasJurczok** [comment]
I didn't expect you to change GitHub :D I just assumed you have way more experience with this than I do.

For the record:
Github support said that this is a bug in the current security filter and should be fixed in the next couple weeks.
